name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release of dist.zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set ENV for github-release
        run: |
          echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
          echo "RELEASE_NAME=$GITHUB_WORKFLOW" >> $GITHUB_ENV

      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 1.7
      - name: Set up Erlang
        uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 22.3.2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Copy the release artifacts
        run: mv clouseau-${{ env.RELEASE_TAG }}.zip clouseau-${{ env.RELEASE_TAG }}-dist.zip